"""
✨ `Interest_KeyOutput` returns the primary key fields of table type `Interest`.

It has the same format as `Interest_Key`, but is only used as mutation return value.
"""
scalar Interest_KeyOutput
"""
✨ `Message_KeyOutput` returns the primary key fields of table type `Message`.

It has the same format as `Message_Key`, but is only used as mutation return value.
"""
scalar Message_KeyOutput
"""
✨ `Photo_KeyOutput` returns the primary key fields of table type `Photo`.

It has the same format as `Photo_Key`, but is only used as mutation return value.
"""
scalar Photo_KeyOutput
"""
✨ `Profile_KeyOutput` returns the primary key fields of table type `Profile`.

It has the same format as `Profile_Key`, but is only used as mutation return value.
"""
scalar Profile_KeyOutput
"""
✨ `SubscriptionType_KeyOutput` returns the primary key fields of table type `SubscriptionType`.

It has the same format as `SubscriptionType_Key`, but is only used as mutation return value.
"""
scalar SubscriptionType_KeyOutput
"""
✨ `User_KeyOutput` returns the primary key fields of table type `User`.

It has the same format as `User_Key`, but is only used as mutation return value.
"""
scalar User_KeyOutput
"""
✨ `UserSubscription_KeyOutput` returns the primary key fields of table type `UserSubscription`.

It has the same format as `UserSubscription_Key`, but is only used as mutation return value.
"""
scalar UserSubscription_KeyOutput
"""
✨ Generated data input type for table 'Interest'. It includes all necessary fields for creating or upserting rows into table.
"""
input Interest_Data {
  """
  ✨ Generated from Field `Interest`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Interest`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Interest`.`receiverId` of type `UUID!`
  """
  receiverId: UUID
  """
  ✨ `_expr` server value variant of `receiverId` (✨ Generated from Field `Interest`.`receiverId` of type `UUID!`)
  """
  receiverId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Interest`.`senderId` of type `UUID!`
  """
  senderId: UUID
  """
  ✨ `_expr` server value variant of `senderId` (✨ Generated from Field `Interest`.`senderId` of type `UUID!`)
  """
  senderId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Interest`.`receiver` of type `User!`
  """
  receiver: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Interest`.`sender` of type `User!`
  """
  sender: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Interest`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Interest`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Interest`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Interest`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Interest`.`status` of type `String!`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `Interest`.`status` of type `String!`)
  """
  status_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Interest'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Interest_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Interest_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Interest_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Interest_Filter!]
  """
  ✨ Generated from Field `Interest`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Interest`.`receiverId` of type `UUID!`
  """
  receiverId: UUID_Filter
  """
  ✨ Generated from Field `Interest`.`senderId` of type `UUID!`
  """
  senderId: UUID_Filter
  """
  ✨ Generated from Field `Interest`.`receiver` of type `User!`
  """
  receiver: User_Filter
  """
  ✨ Generated from Field `Interest`.`sender` of type `User!`
  """
  sender: User_Filter
  """
  ✨ Generated from Field `Interest`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Interest`.`status` of type `String!`
  """
  status: String_Filter
}
"""
✨ Generated first-row input type for table 'Interest'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Interest_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Interest_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Interest_Filter
}
"""
✨ Generated having input type for table 'Interest'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Interest_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Interest_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Interest_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Interest_Having!]
  """
  ✨ Generated from Field `Interest`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Interest`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Interest`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Interest`.`receiverId_count` of type `Int!`
  """
  receiverId_count: Int_Filter
  """
  ✨ Generated from Field `Interest`.`senderId_count` of type `Int!`
  """
  senderId_count: Int_Filter
  """
  ✨ Generated from Field `Interest`.`status_count` of type `Int!`
  """
  status_count: Int_Filter
  """
  ✨ Generated from Field `Interest`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Interest`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Interest'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Interest_Key {
  """
  ✨ Generated from Field `Interest`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Interest`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Interest'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Interest_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Interest_Filter
}
"""
✨ Generated order input type for table 'Interest'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Interest_Order {
  """
  ✨ Generated from Field `Interest`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Interest`.`receiverId` of type `UUID!`
  """
  receiverId: OrderDirection
  """
  ✨ Generated from Field `Interest`.`senderId` of type `UUID!`
  """
  senderId: OrderDirection
  """
  ✨ Generated from Field `Interest`.`receiver` of type `User!`
  """
  receiver: User_Order
  """
  ✨ Generated from Field `Interest`.`sender` of type `User!`
  """
  sender: User_Order
  """
  ✨ Generated from Field `Interest`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Interest`.`status` of type `String!`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `Interest`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Interest`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Interest`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Interest`.`receiverId_count` of type `Int!`
  """
  receiverId_count: OrderDirection
  """
  ✨ Generated from Field `Interest`.`senderId_count` of type `Int!`
  """
  senderId_count: OrderDirection
  """
  ✨ Generated from Field `Interest`.`status_count` of type `Int!`
  """
  status_count: OrderDirection
  """
  ✨ Generated from Field `Interest`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Interest`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Message'. It includes all necessary fields for creating or upserting rows into table.
"""
input Message_Data {
  """
  ✨ Generated from Field `Message`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Message`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Message`.`receiverId` of type `UUID!`
  """
  receiverId: UUID
  """
  ✨ `_expr` server value variant of `receiverId` (✨ Generated from Field `Message`.`receiverId` of type `UUID!`)
  """
  receiverId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Message`.`senderId` of type `UUID!`
  """
  senderId: UUID
  """
  ✨ `_expr` server value variant of `senderId` (✨ Generated from Field `Message`.`senderId` of type `UUID!`)
  """
  senderId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Message`.`receiver` of type `User!`
  """
  receiver: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Message`.`sender` of type `User!`
  """
  sender: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Message`.`content` of type `String!`
  """
  content: String
  """
  ✨ `_expr` server value variant of `content` (✨ Generated from Field `Message`.`content` of type `String!`)
  """
  content_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Message`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Message`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Message`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Message`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Message`.`readAt` of type `Timestamp`
  """
  readAt: Timestamp
  """
  ✨ `_expr` server value variant of `readAt` (✨ Generated from Field `Message`.`readAt` of type `Timestamp`)
  """
  readAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `readAt` (✨ Generated from Field `Message`.`readAt` of type `Timestamp`)
  """
  readAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `readAt` (✨ Generated from Field `Message`.`readAt` of type `Timestamp`)
  """
  readAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Message'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Message_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Message_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Message_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Message_Filter!]
  """
  ✨ Generated from Field `Message`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Message`.`receiverId` of type `UUID!`
  """
  receiverId: UUID_Filter
  """
  ✨ Generated from Field `Message`.`senderId` of type `UUID!`
  """
  senderId: UUID_Filter
  """
  ✨ Generated from Field `Message`.`receiver` of type `User!`
  """
  receiver: User_Filter
  """
  ✨ Generated from Field `Message`.`sender` of type `User!`
  """
  sender: User_Filter
  """
  ✨ Generated from Field `Message`.`content` of type `String!`
  """
  content: String_Filter
  """
  ✨ Generated from Field `Message`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Message`.`readAt` of type `Timestamp`
  """
  readAt: Timestamp_Filter
}
"""
✨ Generated first-row input type for table 'Message'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Message_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Message_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Message_Filter
}
"""
✨ Generated having input type for table 'Message'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Message_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Message_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Message_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Message_Having!]
  """
  ✨ Generated from Field `Message`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Message`.`content_count` of type `Int!`
  """
  content_count: Int_Filter
  """
  ✨ Generated from Field `Message`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Message`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Message`.`readAt_count` of type `Int!`
  """
  readAt_count: Int_Filter
  """
  ✨ Generated from Field `Message`.`receiverId_count` of type `Int!`
  """
  receiverId_count: Int_Filter
  """
  ✨ Generated from Field `Message`.`senderId_count` of type `Int!`
  """
  senderId_count: Int_Filter
  """
  ✨ Generated from Field `Message`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Message`.`readAt_min` of type `Timestamp`
  """
  readAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Message`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `Message`.`readAt_max` of type `Timestamp`
  """
  readAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Message'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Message_Key {
  """
  ✨ Generated from Field `Message`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Message`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Message'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Message_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Message_Filter
}
"""
✨ Generated order input type for table 'Message'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Message_Order {
  """
  ✨ Generated from Field `Message`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Message`.`receiverId` of type `UUID!`
  """
  receiverId: OrderDirection
  """
  ✨ Generated from Field `Message`.`senderId` of type `UUID!`
  """
  senderId: OrderDirection
  """
  ✨ Generated from Field `Message`.`receiver` of type `User!`
  """
  receiver: User_Order
  """
  ✨ Generated from Field `Message`.`sender` of type `User!`
  """
  sender: User_Order
  """
  ✨ Generated from Field `Message`.`content` of type `String!`
  """
  content: OrderDirection
  """
  ✨ Generated from Field `Message`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Message`.`readAt` of type `Timestamp`
  """
  readAt: OrderDirection
  """
  ✨ Generated from Field `Message`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Message`.`content_count` of type `Int!`
  """
  content_count: OrderDirection
  """
  ✨ Generated from Field `Message`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Message`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Message`.`readAt_count` of type `Int!`
  """
  readAt_count: OrderDirection
  """
  ✨ Generated from Field `Message`.`receiverId_count` of type `Int!`
  """
  receiverId_count: OrderDirection
  """
  ✨ Generated from Field `Message`.`senderId_count` of type `Int!`
  """
  senderId_count: OrderDirection
  """
  ✨ Generated from Field `Message`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Message`.`readAt_min` of type `Timestamp`
  """
  readAt_min: OrderDirection
  """
  ✨ Generated from Field `Message`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `Message`.`readAt_max` of type `Timestamp`
  """
  readAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Photo'. It includes all necessary fields for creating or upserting rows into table.
"""
input Photo_Data {
  """
  ✨ Generated from Field `Photo`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Photo`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Photo`.`userId` of type `UUID!`
  """
  userId: UUID
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Photo`.`userId` of type `UUID!`)
  """
  userId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Photo`.`user` of type `User!`
  """
  user: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Photo`.`caption` of type `String`
  """
  caption: String
  """
  ✨ `_expr` server value variant of `caption` (✨ Generated from Field `Photo`.`caption` of type `String`)
  """
  caption_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Photo`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Photo`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Photo`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Photo`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Photo`.`imageUrl` of type `String!`
  """
  imageUrl: String
  """
  ✨ `_expr` server value variant of `imageUrl` (✨ Generated from Field `Photo`.`imageUrl` of type `String!`)
  """
  imageUrl_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Photo`.`isProfilePic` of type `Boolean`
  """
  isProfilePic: Boolean
  """
  ✨ `_expr` server value variant of `isProfilePic` (✨ Generated from Field `Photo`.`isProfilePic` of type `Boolean`)
  """
  isProfilePic_expr: Boolean_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Photo'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Photo_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Photo_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Photo_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Photo_Filter!]
  """
  ✨ Generated from Field `Photo`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Photo`.`userId` of type `UUID!`
  """
  userId: UUID_Filter
  """
  ✨ Generated from Field `Photo`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `Photo`.`caption` of type `String`
  """
  caption: String_Filter
  """
  ✨ Generated from Field `Photo`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Photo`.`imageUrl` of type `String!`
  """
  imageUrl: String_Filter
  """
  ✨ Generated from Field `Photo`.`isProfilePic` of type `Boolean`
  """
  isProfilePic: Boolean_Filter
}
"""
✨ Generated first-row input type for table 'Photo'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Photo_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Photo_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Photo_Filter
}
"""
✨ Generated having input type for table 'Photo'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Photo_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Photo_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Photo_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Photo_Having!]
  """
  ✨ Generated from Field `Photo`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Photo`.`caption_count` of type `Int!`
  """
  caption_count: Int_Filter
  """
  ✨ Generated from Field `Photo`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Photo`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Photo`.`imageUrl_count` of type `Int!`
  """
  imageUrl_count: Int_Filter
  """
  ✨ Generated from Field `Photo`.`isProfilePic_count` of type `Int!`
  """
  isProfilePic_count: Int_Filter
  """
  ✨ Generated from Field `Photo`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
  """
  ✨ Generated from Field `Photo`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Photo`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Photo'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Photo_Key {
  """
  ✨ Generated from Field `Photo`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Photo`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Photo'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Photo_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Photo_Filter
}
"""
✨ Generated order input type for table 'Photo'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Photo_Order {
  """
  ✨ Generated from Field `Photo`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Photo`.`userId` of type `UUID!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `Photo`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `Photo`.`caption` of type `String`
  """
  caption: OrderDirection
  """
  ✨ Generated from Field `Photo`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Photo`.`imageUrl` of type `String!`
  """
  imageUrl: OrderDirection
  """
  ✨ Generated from Field `Photo`.`isProfilePic` of type `Boolean`
  """
  isProfilePic: OrderDirection
  """
  ✨ Generated from Field `Photo`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Photo`.`caption_count` of type `Int!`
  """
  caption_count: OrderDirection
  """
  ✨ Generated from Field `Photo`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Photo`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Photo`.`imageUrl_count` of type `Int!`
  """
  imageUrl_count: OrderDirection
  """
  ✨ Generated from Field `Photo`.`isProfilePic_count` of type `Int!`
  """
  isProfilePic_count: OrderDirection
  """
  ✨ Generated from Field `Photo`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
  """
  ✨ Generated from Field `Photo`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Photo`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Profile'. It includes all necessary fields for creating or upserting rows into table.
"""
input Profile_Data {
  """
  ✨ Generated from Field `Profile`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Profile`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Profile`.`userId` of type `UUID!`
  """
  userId: UUID
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Profile`.`userId` of type `UUID!`)
  """
  userId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Profile`.`user` of type `User!`
  """
  user: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Profile`.`aboutFamily` of type `String`
  """
  aboutFamily: String
  """
  ✨ `_expr` server value variant of `aboutFamily` (✨ Generated from Field `Profile`.`aboutFamily` of type `String`)
  """
  aboutFamily_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Profile`.`community` of type `String!`
  """
  community: String
  """
  ✨ `_expr` server value variant of `community` (✨ Generated from Field `Profile`.`community` of type `String!`)
  """
  community_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Profile`.`dietaryPreferences` of type `String`
  """
  dietaryPreferences: String
  """
  ✨ `_expr` server value variant of `dietaryPreferences` (✨ Generated from Field `Profile`.`dietaryPreferences` of type `String`)
  """
  dietaryPreferences_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Profile`.`familyValues` of type `String`
  """
  familyValues: String
  """
  ✨ `_expr` server value variant of `familyValues` (✨ Generated from Field `Profile`.`familyValues` of type `String`)
  """
  familyValues_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Profile`.`hobbies` of type `[String]`
  """
  hobbies: [String!]
  """
  ✨ `_update` server value variant of `hobbies` (✨ Generated from Field `Profile`.`hobbies` of type `[String]`)
  """
  hobbies_update: [String_ListUpdate!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Profile`.`interests` of type `[String]`
  """
  interests: [String!]
  """
  ✨ `_update` server value variant of `interests` (✨ Generated from Field `Profile`.`interests` of type `[String]`)
  """
  interests_update: [String_ListUpdate!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Profile`.`maritalStatus` of type `String!`
  """
  maritalStatus: String
  """
  ✨ `_expr` server value variant of `maritalStatus` (✨ Generated from Field `Profile`.`maritalStatus` of type `String!`)
  """
  maritalStatus_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Profile`.`motherTongue` of type `String!`
  """
  motherTongue: String
  """
  ✨ `_expr` server value variant of `motherTongue` (✨ Generated from Field `Profile`.`motherTongue` of type `String!`)
  """
  motherTongue_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Profile`.`partnerExpectations` of type `String`
  """
  partnerExpectations: String
  """
  ✨ `_expr` server value variant of `partnerExpectations` (✨ Generated from Field `Profile`.`partnerExpectations` of type `String`)
  """
  partnerExpectations_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Profile`.`wantsChildren` of type `Boolean!`
  """
  wantsChildren: Boolean
  """
  ✨ `_expr` server value variant of `wantsChildren` (✨ Generated from Field `Profile`.`wantsChildren` of type `Boolean!`)
  """
  wantsChildren_expr: Boolean_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Profile'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Profile_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Profile_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Profile_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Profile_Filter!]
  """
  ✨ Generated from Field `Profile`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Profile`.`userId` of type `UUID!`
  """
  userId: UUID_Filter
  """
  ✨ Generated from Field `Profile`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `Profile`.`aboutFamily` of type `String`
  """
  aboutFamily: String_Filter
  """
  ✨ Generated from Field `Profile`.`community` of type `String!`
  """
  community: String_Filter
  """
  ✨ Generated from Field `Profile`.`dietaryPreferences` of type `String`
  """
  dietaryPreferences: String_Filter
  """
  ✨ Generated from Field `Profile`.`familyValues` of type `String`
  """
  familyValues: String_Filter
  """
  ✨ Generated from Field `Profile`.`hobbies` of type `[String]`
  """
  hobbies: String_ListFilter
  """
  ✨ Generated from Field `Profile`.`interests` of type `[String]`
  """
  interests: String_ListFilter
  """
  ✨ Generated from Field `Profile`.`maritalStatus` of type `String!`
  """
  maritalStatus: String_Filter
  """
  ✨ Generated from Field `Profile`.`motherTongue` of type `String!`
  """
  motherTongue: String_Filter
  """
  ✨ Generated from Field `Profile`.`partnerExpectations` of type `String`
  """
  partnerExpectations: String_Filter
  """
  ✨ Generated from Field `Profile`.`wantsChildren` of type `Boolean!`
  """
  wantsChildren: Boolean_Filter
}
"""
✨ Generated first-row input type for table 'Profile'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Profile_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Profile_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Profile_Filter
}
"""
✨ Generated having input type for table 'Profile'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Profile_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Profile_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Profile_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Profile_Having!]
  """
  ✨ Generated from Field `Profile`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`aboutFamily_count` of type `Int!`
  """
  aboutFamily_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`community_count` of type `Int!`
  """
  community_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`dietaryPreferences_count` of type `Int!`
  """
  dietaryPreferences_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`familyValues_count` of type `Int!`
  """
  familyValues_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`maritalStatus_count` of type `Int!`
  """
  maritalStatus_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`motherTongue_count` of type `Int!`
  """
  motherTongue_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`partnerExpectations_count` of type `Int!`
  """
  partnerExpectations_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`wantsChildren_count` of type `Int!`
  """
  wantsChildren_count: Int_Filter
}
"""
✨ Generated key input type for table 'Profile'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Profile_Key {
  """
  ✨ Generated from Field `Profile`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Profile`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Profile'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Profile_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Profile_Filter
}
"""
✨ Generated order input type for table 'Profile'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Profile_Order {
  """
  ✨ Generated from Field `Profile`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Profile`.`userId` of type `UUID!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `Profile`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `Profile`.`aboutFamily` of type `String`
  """
  aboutFamily: OrderDirection
  """
  ✨ Generated from Field `Profile`.`community` of type `String!`
  """
  community: OrderDirection
  """
  ✨ Generated from Field `Profile`.`dietaryPreferences` of type `String`
  """
  dietaryPreferences: OrderDirection
  """
  ✨ Generated from Field `Profile`.`familyValues` of type `String`
  """
  familyValues: OrderDirection
  """
  ✨ Generated from Field `Profile`.`maritalStatus` of type `String!`
  """
  maritalStatus: OrderDirection
  """
  ✨ Generated from Field `Profile`.`motherTongue` of type `String!`
  """
  motherTongue: OrderDirection
  """
  ✨ Generated from Field `Profile`.`partnerExpectations` of type `String`
  """
  partnerExpectations: OrderDirection
  """
  ✨ Generated from Field `Profile`.`wantsChildren` of type `Boolean!`
  """
  wantsChildren: OrderDirection
  """
  ✨ Generated from Field `Profile`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`aboutFamily_count` of type `Int!`
  """
  aboutFamily_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`community_count` of type `Int!`
  """
  community_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`dietaryPreferences_count` of type `Int!`
  """
  dietaryPreferences_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`familyValues_count` of type `Int!`
  """
  familyValues_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`maritalStatus_count` of type `Int!`
  """
  maritalStatus_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`motherTongue_count` of type `Int!`
  """
  motherTongue_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`partnerExpectations_count` of type `Int!`
  """
  partnerExpectations_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`wantsChildren_count` of type `Int!`
  """
  wantsChildren_count: OrderDirection
}
"""
✨ Generated data input type for table 'SubscriptionType'. It includes all necessary fields for creating or upserting rows into table.
"""
input SubscriptionType_Data {
  """
  ✨ Generated from Field `SubscriptionType`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `SubscriptionType`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SubscriptionType`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `SubscriptionType`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `SubscriptionType`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `SubscriptionType`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SubscriptionType`.`durationInDays` of type `Int!`
  """
  durationInDays: Int
  """
  ✨ `_expr` server value variant of `durationInDays` (✨ Generated from Field `SubscriptionType`.`durationInDays` of type `Int!`)
  """
  durationInDays_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `durationInDays` (✨ Generated from Field `SubscriptionType`.`durationInDays` of type `Int!`)
  """
  durationInDays_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SubscriptionType`.`features` of type `[String]`
  """
  features: [String!]
  """
  ✨ `_update` server value variant of `features` (✨ Generated from Field `SubscriptionType`.`features` of type `[String]`)
  """
  features_update: [String_ListUpdate!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SubscriptionType`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `SubscriptionType`.`name` of type `String!`)
  """
  name_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `SubscriptionType`.`price` of type `Float!`
  """
  price: Float
  """
  ✨ `_expr` server value variant of `price` (✨ Generated from Field `SubscriptionType`.`price` of type `Float!`)
  """
  price_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `price` (✨ Generated from Field `SubscriptionType`.`price` of type `Float!`)
  """
  price_update: [Float_Update!] @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'SubscriptionType'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input SubscriptionType_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [SubscriptionType_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: SubscriptionType_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [SubscriptionType_Filter!]
  """
  ✨ Generated from Field `SubscriptionType`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`durationInDays` of type `Int!`
  """
  durationInDays: Int_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`features` of type `[String]`
  """
  features: String_ListFilter
  """
  ✨ Generated from Field `SubscriptionType`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`price` of type `Float!`
  """
  price: Float_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`userSubscriptions_on_subscriptionType` of type `[UserSubscription!]!`
  """
  userSubscriptions_on_subscriptionType: UserSubscription_ListFilter
}
"""
✨ Generated first-row input type for table 'SubscriptionType'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input SubscriptionType_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [SubscriptionType_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: SubscriptionType_Filter
}
"""
✨ Generated having input type for table 'SubscriptionType'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input SubscriptionType_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [SubscriptionType_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: SubscriptionType_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [SubscriptionType_Having!]
  """
  ✨ Generated from Field `SubscriptionType`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`durationInDays_count` of type `Int!`
  """
  durationInDays_count: Int_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`price_count` of type `Int!`
  """
  price_count: Int_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`durationInDays_sum` of type `Int`
  """
  durationInDays_sum: Int_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`price_sum` of type `Float`
  """
  price_sum: Float_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`durationInDays_avg` of type `Float`
  """
  durationInDays_avg: Float_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`price_avg` of type `Float`
  """
  price_avg: Float_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`durationInDays_min` of type `Int`
  """
  durationInDays_min: Int_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`price_min` of type `Float`
  """
  price_min: Float_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`durationInDays_max` of type `Int`
  """
  durationInDays_max: Int_Filter
  """
  ✨ Generated from Field `SubscriptionType`.`price_max` of type `Float`
  """
  price_max: Float_Filter
}
"""
✨ Generated key input type for table 'SubscriptionType'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input SubscriptionType_Key {
  """
  ✨ Generated from Field `SubscriptionType`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `SubscriptionType`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'SubscriptionType'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input SubscriptionType_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: SubscriptionType_Filter
}
"""
✨ Generated order input type for table 'SubscriptionType'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input SubscriptionType_Order {
  """
  ✨ Generated from Field `SubscriptionType`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`durationInDays` of type `Int!`
  """
  durationInDays: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`price` of type `Float!`
  """
  price: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`durationInDays_count` of type `Int!`
  """
  durationInDays_count: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`price_count` of type `Int!`
  """
  price_count: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`durationInDays_sum` of type `Int`
  """
  durationInDays_sum: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`price_sum` of type `Float`
  """
  price_sum: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`durationInDays_avg` of type `Float`
  """
  durationInDays_avg: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`price_avg` of type `Float`
  """
  price_avg: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`durationInDays_min` of type `Int`
  """
  durationInDays_min: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`price_min` of type `Float`
  """
  price_min: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`durationInDays_max` of type `Int`
  """
  durationInDays_max: OrderDirection
  """
  ✨ Generated from Field `SubscriptionType`.`price_max` of type `Float`
  """
  price_max: OrderDirection
}
"""
✨ Generated data input type for table 'User'. It includes all necessary fields for creating or upserting rows into table.
"""
input User_Data {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`bio` of type `String`
  """
  bio: String
  """
  ✨ `_expr` server value variant of `bio` (✨ Generated from Field `User`.`bio` of type `String`)
  """
  bio_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`city` of type `String`
  """
  city: String
  """
  ✨ `_expr` server value variant of `city` (✨ Generated from Field `User`.`city` of type `String`)
  """
  city_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`country` of type `String`
  """
  country: String
  """
  ✨ `_expr` server value variant of `country` (✨ Generated from Field `User`.`country` of type `String`)
  """
  country_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: String
  """
  ✨ `_expr` server value variant of `displayName` (✨ Generated from Field `User`.`displayName` of type `String!`)
  """
  displayName_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`dob` of type `Date!`
  """
  dob: Date
  """
  ✨ `_date` server value variant of `dob` (✨ Generated from Field `User`.`dob` of type `Date!`)
  """
  dob_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `dob` (✨ Generated from Field `User`.`dob` of type `Date!`)
  """
  dob_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `dob` (✨ Generated from Field `User`.`dob` of type `Date!`)
  """
  dob_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`education` of type `String`
  """
  education: String
  """
  ✨ `_expr` server value variant of `education` (✨ Generated from Field `User`.`education` of type `String`)
  """
  education_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `User`.`email` of type `String!`)
  """
  email_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`gender` of type `String!`
  """
  gender: String
  """
  ✨ `_expr` server value variant of `gender` (✨ Generated from Field `User`.`gender` of type `String!`)
  """
  gender_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`height` of type `Float`
  """
  height: Float
  """
  ✨ `_expr` server value variant of `height` (✨ Generated from Field `User`.`height` of type `Float`)
  """
  height_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `height` (✨ Generated from Field `User`.`height` of type `Float`)
  """
  height_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`lastLoginAt` of type `Timestamp`
  """
  lastLoginAt: Timestamp
  """
  ✨ `_expr` server value variant of `lastLoginAt` (✨ Generated from Field `User`.`lastLoginAt` of type `Timestamp`)
  """
  lastLoginAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `lastLoginAt` (✨ Generated from Field `User`.`lastLoginAt` of type `Timestamp`)
  """
  lastLoginAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `lastLoginAt` (✨ Generated from Field `User`.`lastLoginAt` of type `Timestamp`)
  """
  lastLoginAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`lookingForGender` of type `String!`
  """
  lookingForGender: String
  """
  ✨ `_expr` server value variant of `lookingForGender` (✨ Generated from Field `User`.`lookingForGender` of type `String!`)
  """
  lookingForGender_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`passwordHash` of type `String!`
  """
  passwordHash: String
  """
  ✨ `_expr` server value variant of `passwordHash` (✨ Generated from Field `User`.`passwordHash` of type `String!`)
  """
  passwordHash_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: String
  """
  ✨ `_expr` server value variant of `photoUrl` (✨ Generated from Field `User`.`photoUrl` of type `String`)
  """
  photoUrl_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`profession` of type `String`
  """
  profession: String
  """
  ✨ `_expr` server value variant of `profession` (✨ Generated from Field `User`.`profession` of type `String`)
  """
  profession_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`religion` of type `String`
  """
  religion: String
  """
  ✨ `_expr` server value variant of `religion` (✨ Generated from Field `User`.`religion` of type `String`)
  """
  religion_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'User'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [User_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: User_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [User_Filter!]
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `User`.`bio` of type `String`
  """
  bio: String_Filter
  """
  ✨ Generated from Field `User`.`city` of type `String`
  """
  city: String_Filter
  """
  ✨ Generated from Field `User`.`country` of type `String`
  """
  country: String_Filter
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: String_Filter
  """
  ✨ Generated from Field `User`.`dob` of type `Date!`
  """
  dob: Date_Filter
  """
  ✨ Generated from Field `User`.`education` of type `String`
  """
  education: String_Filter
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: String_Filter
  """
  ✨ Generated from Field `User`.`gender` of type `String!`
  """
  gender: String_Filter
  """
  ✨ Generated from Field `User`.`height` of type `Float`
  """
  height: Float_Filter
  """
  ✨ Generated from Field `User`.`lastLoginAt` of type `Timestamp`
  """
  lastLoginAt: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`lookingForGender` of type `String!`
  """
  lookingForGender: String_Filter
  """
  ✨ Generated from Field `User`.`passwordHash` of type `String!`
  """
  passwordHash: String_Filter
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: String_Filter
  """
  ✨ Generated from Field `User`.`profession` of type `String`
  """
  profession: String_Filter
  """
  ✨ Generated from Field `User`.`religion` of type `String`
  """
  religion: String_Filter
  """
  ✨ Generated from Field `User`.`interests_on_receiver` of type `[Interest!]!`
  """
  interests_on_receiver: Interest_ListFilter
  """
  ✨ Generated from Field `User`.`interests_on_sender` of type `[Interest!]!`
  """
  interests_on_sender: Interest_ListFilter
  """
  ✨ Generated from Field `User`.`messages_on_receiver` of type `[Message!]!`
  """
  messages_on_receiver: Message_ListFilter
  """
  ✨ Generated from Field `User`.`messages_on_sender` of type `[Message!]!`
  """
  messages_on_sender: Message_ListFilter
  """
  ✨ Generated from Field `User`.`photos_on_user` of type `[Photo!]!`
  """
  photos_on_user: Photo_ListFilter
  """
  ✨ Generated from Field `User`.`profiles_on_user` of type `[Profile!]!`
  """
  profiles_on_user: Profile_ListFilter
  """
  ✨ Generated from Field `User`.`userSubscriptions_on_user` of type `[UserSubscription!]!`
  """
  userSubscriptions_on_user: UserSubscription_ListFilter
}
"""
✨ Generated first-row input type for table 'User'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input User_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [User_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: User_Filter
}
"""
✨ Generated having input type for table 'User'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [User_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: User_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [User_Having!]
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `User`.`bio_count` of type `Int!`
  """
  bio_count: Int_Filter
  """
  ✨ Generated from Field `User`.`city_count` of type `Int!`
  """
  city_count: Int_Filter
  """
  ✨ Generated from Field `User`.`country_count` of type `Int!`
  """
  country_count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `User`.`displayName_count` of type `Int!`
  """
  displayName_count: Int_Filter
  """
  ✨ Generated from Field `User`.`dob_count` of type `Int!`
  """
  dob_count: Int_Filter
  """
  ✨ Generated from Field `User`.`education_count` of type `Int!`
  """
  education_count: Int_Filter
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: Int_Filter
  """
  ✨ Generated from Field `User`.`gender_count` of type `Int!`
  """
  gender_count: Int_Filter
  """
  ✨ Generated from Field `User`.`height_count` of type `Int!`
  """
  height_count: Int_Filter
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `User`.`lastLoginAt_count` of type `Int!`
  """
  lastLoginAt_count: Int_Filter
  """
  ✨ Generated from Field `User`.`lookingForGender_count` of type `Int!`
  """
  lookingForGender_count: Int_Filter
  """
  ✨ Generated from Field `User`.`passwordHash_count` of type `Int!`
  """
  passwordHash_count: Int_Filter
  """
  ✨ Generated from Field `User`.`photoUrl_count` of type `Int!`
  """
  photoUrl_count: Int_Filter
  """
  ✨ Generated from Field `User`.`profession_count` of type `Int!`
  """
  profession_count: Int_Filter
  """
  ✨ Generated from Field `User`.`religion_count` of type `Int!`
  """
  religion_count: Int_Filter
  """
  ✨ Generated from Field `User`.`height_sum` of type `Float`
  """
  height_sum: Float_Filter
  """
  ✨ Generated from Field `User`.`height_avg` of type `Float`
  """
  height_avg: Float_Filter
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`dob_min` of type `Date`
  """
  dob_min: Date_Filter
  """
  ✨ Generated from Field `User`.`height_min` of type `Float`
  """
  height_min: Float_Filter
  """
  ✨ Generated from Field `User`.`lastLoginAt_min` of type `Timestamp`
  """
  lastLoginAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`dob_max` of type `Date`
  """
  dob_max: Date_Filter
  """
  ✨ Generated from Field `User`.`height_max` of type `Float`
  """
  height_max: Float_Filter
  """
  ✨ Generated from Field `User`.`lastLoginAt_max` of type `Timestamp`
  """
  lastLoginAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'User'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input User_Key {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'User'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input User_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: User_Filter
}
"""
✨ Generated order input type for table 'User'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input User_Order {
  """
  ✨ Generated from Field `User`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `User`.`bio` of type `String`
  """
  bio: OrderDirection
  """
  ✨ Generated from Field `User`.`city` of type `String`
  """
  city: OrderDirection
  """
  ✨ Generated from Field `User`.`country` of type `String`
  """
  country: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `User`.`displayName` of type `String!`
  """
  displayName: OrderDirection
  """
  ✨ Generated from Field `User`.`dob` of type `Date!`
  """
  dob: OrderDirection
  """
  ✨ Generated from Field `User`.`education` of type `String`
  """
  education: OrderDirection
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `User`.`gender` of type `String!`
  """
  gender: OrderDirection
  """
  ✨ Generated from Field `User`.`height` of type `Float`
  """
  height: OrderDirection
  """
  ✨ Generated from Field `User`.`lastLoginAt` of type `Timestamp`
  """
  lastLoginAt: OrderDirection
  """
  ✨ Generated from Field `User`.`lookingForGender` of type `String!`
  """
  lookingForGender: OrderDirection
  """
  ✨ Generated from Field `User`.`passwordHash` of type `String!`
  """
  passwordHash: OrderDirection
  """
  ✨ Generated from Field `User`.`photoUrl` of type `String`
  """
  photoUrl: OrderDirection
  """
  ✨ Generated from Field `User`.`profession` of type `String`
  """
  profession: OrderDirection
  """
  ✨ Generated from Field `User`.`religion` of type `String`
  """
  religion: OrderDirection
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `User`.`bio_count` of type `Int!`
  """
  bio_count: OrderDirection
  """
  ✨ Generated from Field `User`.`city_count` of type `Int!`
  """
  city_count: OrderDirection
  """
  ✨ Generated from Field `User`.`country_count` of type `Int!`
  """
  country_count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `User`.`displayName_count` of type `Int!`
  """
  displayName_count: OrderDirection
  """
  ✨ Generated from Field `User`.`dob_count` of type `Int!`
  """
  dob_count: OrderDirection
  """
  ✨ Generated from Field `User`.`education_count` of type `Int!`
  """
  education_count: OrderDirection
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: OrderDirection
  """
  ✨ Generated from Field `User`.`gender_count` of type `Int!`
  """
  gender_count: OrderDirection
  """
  ✨ Generated from Field `User`.`height_count` of type `Int!`
  """
  height_count: OrderDirection
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `User`.`lastLoginAt_count` of type `Int!`
  """
  lastLoginAt_count: OrderDirection
  """
  ✨ Generated from Field `User`.`lookingForGender_count` of type `Int!`
  """
  lookingForGender_count: OrderDirection
  """
  ✨ Generated from Field `User`.`passwordHash_count` of type `Int!`
  """
  passwordHash_count: OrderDirection
  """
  ✨ Generated from Field `User`.`photoUrl_count` of type `Int!`
  """
  photoUrl_count: OrderDirection
  """
  ✨ Generated from Field `User`.`profession_count` of type `Int!`
  """
  profession_count: OrderDirection
  """
  ✨ Generated from Field `User`.`religion_count` of type `Int!`
  """
  religion_count: OrderDirection
  """
  ✨ Generated from Field `User`.`height_sum` of type `Float`
  """
  height_sum: OrderDirection
  """
  ✨ Generated from Field `User`.`height_avg` of type `Float`
  """
  height_avg: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `User`.`dob_min` of type `Date`
  """
  dob_min: OrderDirection
  """
  ✨ Generated from Field `User`.`height_min` of type `Float`
  """
  height_min: OrderDirection
  """
  ✨ Generated from Field `User`.`lastLoginAt_min` of type `Timestamp`
  """
  lastLoginAt_min: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `User`.`dob_max` of type `Date`
  """
  dob_max: OrderDirection
  """
  ✨ Generated from Field `User`.`height_max` of type `Float`
  """
  height_max: OrderDirection
  """
  ✨ Generated from Field `User`.`lastLoginAt_max` of type `Timestamp`
  """
  lastLoginAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'UserSubscription'. It includes all necessary fields for creating or upserting rows into table.
"""
input UserSubscription_Data {
  """
  ✨ Generated from Field `UserSubscription`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `UserSubscription`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserSubscription`.`subscriptionTypeId` of type `UUID!`
  """
  subscriptionTypeId: UUID
  """
  ✨ `_expr` server value variant of `subscriptionTypeId` (✨ Generated from Field `UserSubscription`.`subscriptionTypeId` of type `UUID!`)
  """
  subscriptionTypeId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserSubscription`.`userId` of type `UUID!`
  """
  userId: UUID
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `UserSubscription`.`userId` of type `UUID!`)
  """
  userId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserSubscription`.`subscriptionType` of type `SubscriptionType!`
  """
  subscriptionType: SubscriptionType_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserSubscription`.`user` of type `User!`
  """
  user: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserSubscription`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `UserSubscription`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `UserSubscription`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `UserSubscription`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserSubscription`.`endDate` of type `Timestamp!`
  """
  endDate: Timestamp
  """
  ✨ `_expr` server value variant of `endDate` (✨ Generated from Field `UserSubscription`.`endDate` of type `Timestamp!`)
  """
  endDate_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `endDate` (✨ Generated from Field `UserSubscription`.`endDate` of type `Timestamp!`)
  """
  endDate_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `endDate` (✨ Generated from Field `UserSubscription`.`endDate` of type `Timestamp!`)
  """
  endDate_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `UserSubscription`.`startDate` of type `Timestamp!`
  """
  startDate: Timestamp
  """
  ✨ `_expr` server value variant of `startDate` (✨ Generated from Field `UserSubscription`.`startDate` of type `Timestamp!`)
  """
  startDate_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `startDate` (✨ Generated from Field `UserSubscription`.`startDate` of type `Timestamp!`)
  """
  startDate_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `startDate` (✨ Generated from Field `UserSubscription`.`startDate` of type `Timestamp!`)
  """
  startDate_update: [Timestamp_Update!] @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'UserSubscription'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input UserSubscription_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [UserSubscription_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: UserSubscription_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [UserSubscription_Filter!]
  """
  ✨ Generated from Field `UserSubscription`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `UserSubscription`.`subscriptionTypeId` of type `UUID!`
  """
  subscriptionTypeId: UUID_Filter
  """
  ✨ Generated from Field `UserSubscription`.`userId` of type `UUID!`
  """
  userId: UUID_Filter
  """
  ✨ Generated from Field `UserSubscription`.`subscriptionType` of type `SubscriptionType!`
  """
  subscriptionType: SubscriptionType_Filter
  """
  ✨ Generated from Field `UserSubscription`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `UserSubscription`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `UserSubscription`.`endDate` of type `Timestamp!`
  """
  endDate: Timestamp_Filter
  """
  ✨ Generated from Field `UserSubscription`.`startDate` of type `Timestamp!`
  """
  startDate: Timestamp_Filter
}
"""
✨ Generated first-row input type for table 'UserSubscription'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input UserSubscription_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [UserSubscription_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: UserSubscription_Filter
}
"""
✨ Generated having input type for table 'UserSubscription'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input UserSubscription_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [UserSubscription_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: UserSubscription_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [UserSubscription_Having!]
  """
  ✨ Generated from Field `UserSubscription`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `UserSubscription`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `UserSubscription`.`endDate_count` of type `Int!`
  """
  endDate_count: Int_Filter
  """
  ✨ Generated from Field `UserSubscription`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `UserSubscription`.`startDate_count` of type `Int!`
  """
  startDate_count: Int_Filter
  """
  ✨ Generated from Field `UserSubscription`.`subscriptionTypeId_count` of type `Int!`
  """
  subscriptionTypeId_count: Int_Filter
  """
  ✨ Generated from Field `UserSubscription`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
  """
  ✨ Generated from Field `UserSubscription`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `UserSubscription`.`endDate_min` of type `Timestamp`
  """
  endDate_min: Timestamp_Filter
  """
  ✨ Generated from Field `UserSubscription`.`startDate_min` of type `Timestamp`
  """
  startDate_min: Timestamp_Filter
  """
  ✨ Generated from Field `UserSubscription`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `UserSubscription`.`endDate_max` of type `Timestamp`
  """
  endDate_max: Timestamp_Filter
  """
  ✨ Generated from Field `UserSubscription`.`startDate_max` of type `Timestamp`
  """
  startDate_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'UserSubscription'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input UserSubscription_Key {
  """
  ✨ Generated from Field `UserSubscription`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `UserSubscription`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'UserSubscription'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input UserSubscription_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: UserSubscription_Filter
}
"""
✨ Generated order input type for table 'UserSubscription'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input UserSubscription_Order {
  """
  ✨ Generated from Field `UserSubscription`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`subscriptionTypeId` of type `UUID!`
  """
  subscriptionTypeId: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`userId` of type `UUID!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`subscriptionType` of type `SubscriptionType!`
  """
  subscriptionType: SubscriptionType_Order
  """
  ✨ Generated from Field `UserSubscription`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `UserSubscription`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`endDate` of type `Timestamp!`
  """
  endDate: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`startDate` of type `Timestamp!`
  """
  startDate: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`endDate_count` of type `Int!`
  """
  endDate_count: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`startDate_count` of type `Int!`
  """
  startDate_count: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`subscriptionTypeId_count` of type `Int!`
  """
  subscriptionTypeId_count: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`endDate_min` of type `Timestamp`
  """
  endDate_min: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`startDate_min` of type `Timestamp`
  """
  startDate_min: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`endDate_max` of type `Timestamp`
  """
  endDate_max: OrderDirection
  """
  ✨ Generated from Field `UserSubscription`.`startDate_max` of type `Timestamp`
  """
  startDate_max: OrderDirection
}
