extend type Mutation {
  """
  ✨ Insert a single `Interest` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  interest_insert(
    """
    Data object to insert into the table.
    """
    data: Interest_Data!
  ): Interest_KeyOutput! @fdc_generated(from: "Interest", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Message` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  message_insert(
    """
    Data object to insert into the table.
    """
    data: Message_Data!
  ): Message_KeyOutput! @fdc_generated(from: "Message", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Photo` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  photo_insert(
    """
    Data object to insert into the table.
    """
    data: Photo_Data!
  ): Photo_KeyOutput! @fdc_generated(from: "Photo", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Profile` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  profile_insert(
    """
    Data object to insert into the table.
    """
    data: Profile_Data!
  ): Profile_KeyOutput! @fdc_generated(from: "Profile", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `SubscriptionType` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  subscriptionType_insert(
    """
    Data object to insert into the table.
    """
    data: SubscriptionType_Data!
  ): SubscriptionType_KeyOutput! @fdc_generated(from: "SubscriptionType", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserSubscription` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userSubscription_insert(
    """
    Data object to insert into the table.
    """
    data: UserSubscription_Data!
  ): UserSubscription_KeyOutput! @fdc_generated(from: "UserSubscription", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Interest` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  interest_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Interest_Data!]!
  ): [Interest_KeyOutput!]! @fdc_generated(from: "Interest", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Message` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  message_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Message_Data!]!
  ): [Message_KeyOutput!]! @fdc_generated(from: "Message", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Photo` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  photo_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Photo_Data!]!
  ): [Photo_KeyOutput!]! @fdc_generated(from: "Photo", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Profile` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  profile_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Profile_Data!]!
  ): [Profile_KeyOutput!]! @fdc_generated(from: "Profile", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `SubscriptionType` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  subscriptionType_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [SubscriptionType_Data!]!
  ): [SubscriptionType_KeyOutput!]! @fdc_generated(from: "SubscriptionType", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserSubscription` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userSubscription_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserSubscription_Data!]!
  ): [UserSubscription_KeyOutput!]! @fdc_generated(from: "UserSubscription", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Interest` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Interest`.
  """
  interest_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Interest_Data!
  ): Interest_KeyOutput! @fdc_generated(from: "Interest", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Message` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Message`.
  """
  message_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Message_Data!
  ): Message_KeyOutput! @fdc_generated(from: "Message", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Photo` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Photo`.
  """
  photo_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Photo_Data!
  ): Photo_KeyOutput! @fdc_generated(from: "Photo", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Profile` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Profile`.
  """
  profile_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Profile_Data!
  ): Profile_KeyOutput! @fdc_generated(from: "Profile", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `SubscriptionType` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SubscriptionType`.
  """
  subscriptionType_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: SubscriptionType_Data!
  ): SubscriptionType_KeyOutput! @fdc_generated(from: "SubscriptionType", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserSubscription` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserSubscription`.
  """
  userSubscription_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserSubscription_Data!
  ): UserSubscription_KeyOutput! @fdc_generated(from: "UserSubscription", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Interest` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Interest`.
  """
  interest_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Interest_Data!]!
  ): [Interest_KeyOutput!]! @fdc_generated(from: "Interest", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Message` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Message`.
  """
  message_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Message_Data!]!
  ): [Message_KeyOutput!]! @fdc_generated(from: "Message", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Photo` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Photo`.
  """
  photo_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Photo_Data!]!
  ): [Photo_KeyOutput!]! @fdc_generated(from: "Photo", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Profile` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Profile`.
  """
  profile_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Profile_Data!]!
  ): [Profile_KeyOutput!]! @fdc_generated(from: "Profile", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `SubscriptionType` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SubscriptionType`.
  """
  subscriptionType_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [SubscriptionType_Data!]!
  ): [SubscriptionType_KeyOutput!]! @fdc_generated(from: "SubscriptionType", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserSubscription` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserSubscription`.
  """
  userSubscription_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserSubscription_Data!]!
  ): [UserSubscription_KeyOutput!]! @fdc_generated(from: "UserSubscription", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Interest` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Interest` or `null` if not found.
  """
  interest_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Interest_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Interest_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Interest_Data!
  ): Interest_KeyOutput @fdc_generated(from: "Interest", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Message` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Message` or `null` if not found.
  """
  message_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Message_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Message_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Message_Data!
  ): Message_KeyOutput @fdc_generated(from: "Message", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Photo` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Photo` or `null` if not found.
  """
  photo_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Photo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Photo_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Photo_Data!
  ): Photo_KeyOutput @fdc_generated(from: "Photo", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Profile` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Profile` or `null` if not found.
  """
  profile_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Profile_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Profile_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Profile_Data!
  ): Profile_KeyOutput @fdc_generated(from: "Profile", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `SubscriptionType` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `SubscriptionType` or `null` if not found.
  """
  subscriptionType_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SubscriptionType_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SubscriptionType_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: SubscriptionType_Data!
  ): SubscriptionType_KeyOutput @fdc_generated(from: "SubscriptionType", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserSubscription` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserSubscription` or `null` if not found.
  """
  userSubscription_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserSubscription_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserSubscription_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserSubscription_Data!
  ): UserSubscription_KeyOutput @fdc_generated(from: "UserSubscription", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Interest` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  interest_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Interest_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Interest_Data!
  ): Int! @fdc_generated(from: "Interest", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Message` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  message_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Message_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Message_Data!
  ): Int! @fdc_generated(from: "Message", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Photo` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  photo_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Photo_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Photo_Data!
  ): Int! @fdc_generated(from: "Photo", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Profile` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  profile_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Profile_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Profile_Data!
  ): Int! @fdc_generated(from: "Profile", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `SubscriptionType` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  subscriptionType_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: SubscriptionType_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: SubscriptionType_Data!
  ): Int! @fdc_generated(from: "SubscriptionType", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserSubscription` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userSubscription_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserSubscription_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserSubscription_Data!
  ): Int! @fdc_generated(from: "UserSubscription", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Interest` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  interest_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Interest_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Interest_FirstRow
  ): Interest_KeyOutput @fdc_generated(from: "Interest", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Message` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  message_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Message_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Message_FirstRow
  ): Message_KeyOutput @fdc_generated(from: "Message", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Photo` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  photo_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Photo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Photo_FirstRow
  ): Photo_KeyOutput @fdc_generated(from: "Photo", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Profile` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  profile_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Profile_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Profile_FirstRow
  ): Profile_KeyOutput @fdc_generated(from: "Profile", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `SubscriptionType` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  subscriptionType_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SubscriptionType_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SubscriptionType_FirstRow
  ): SubscriptionType_KeyOutput @fdc_generated(from: "SubscriptionType", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserSubscription` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userSubscription_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserSubscription_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserSubscription_FirstRow
  ): UserSubscription_KeyOutput @fdc_generated(from: "UserSubscription", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Interest` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  interest_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Interest_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Interest", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Message` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  message_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Message_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Message", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Photo` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  photo_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Photo_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Photo", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Profile` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  profile_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Profile_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Profile", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `SubscriptionType` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  subscriptionType_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: SubscriptionType_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "SubscriptionType", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserSubscription` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userSubscription_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserSubscription_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserSubscription", purpose: DELETE_MULTIPLE)
}
