import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'matchmitra_language';

export const supportedLanguages = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिंदी' },
  { code: 'mr', label: 'मराठी' },
];

const translations = {
  en: {
    'language.label': 'Language',
    'language.english': 'English',
    'language.hindi': 'Hindi',
    'language.marathi': 'Marathi',
    'nav.dashboard': 'Dashboard',
    'nav.matches': 'Matches',
    'nav.profile': 'Profile',
    'nav.chat': 'Chat',
    'nav.testimonials': 'Testimonials',
    'nav.logout': 'Logout',
    'footer.rights': '© {year} All rights are reserved by the MatchMitra.',
    'profile.rating': 'Profile Rating',
    'profile.profileScoreHelp': 'This rating helps suggest how complete and trusted the profile looks.',
    'profile.basicInfo': 'Basic Information',
    'profile.professional': 'Professional',
    'profile.aboutMe': 'About Me',
    'profile.interests': 'Interests',
    'profile.family': 'Family',
    'profile.partnerPreferences': 'Partner Preferences',
    'profile.willingToRelocate': 'Willing to relocate',
    'profile.noValue': 'Not provided',
    'profile.age': 'Age',
    'profile.gender': 'Gender',
    'profile.location': 'Location',
    'profile.height': 'Height',
    'profile.maritalStatus': 'Marital Status',
    'profile.profession': 'Profession',
    'profile.education': 'Education',
    'profile.language': 'Language',
    'profile.religion': 'Religion',
    'profile.caste': 'Caste',
    'profile.minAge': 'Min Age',
    'profile.maxAge': 'Max Age',
    'profile.partnerLocation': 'Location',
    'profile.photo': 'Profile Photo',
    'profile.name': 'Name',
    'profile.createProfile': 'Create Your Profile',
    'profile.editProfile': 'Edit Your Profile',
    'profile.updateDetails': 'Update your details anytime.',
    'profile.completeDetails': 'Complete your details to unlock better matches.',
    'profile.completion': 'Completion',
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Track your journey to meaningful matches from one clean overview.',
    'dashboard.yourProfile': 'Your Profile',
    'dashboard.trustScore': 'Trust Score',
    'dashboard.profileViews': 'Profile Views',
    'dashboard.pendingInterests': 'Pending Interests',
    'dashboard.acceptedMatches': 'Accepted Matches',
    'dashboard.activeChats': 'Active Chats',
    'dashboard.interestsReceived': 'Interests Received',
    'dashboard.interestsSubtitle': 'Review requests and respond when ready.',
    'dashboard.recentlyViewed': 'Recently Viewed',
    'dashboard.recentlyViewedSubtitle': 'Profiles you recently opened from cards.',
    'dashboard.noRecentlyViewed': 'No recently viewed profiles yet.',
    'dashboard.suggestedMatches': 'Suggested Matches',
    'dashboard.suggestedSubtitle': 'New people that fit your profile preferences.',
    'dashboard.openMatches': 'Open Matches page →',
    'dashboard.viewAllMatches': 'View all matches →',
    'dashboard.recentMessages': 'Recent Messages',
    'dashboard.recentMessagesSubtitle': 'A quick look at your latest conversations.',
    'dashboard.viewAllChats': 'View all chats →',
    'dashboard.noActiveChats': 'No active chats yet.',
    'dashboard.noMatches': 'No matches available.',
    'dashboard.noInterests': 'No interests received yet.',
    'dashboard.viewAllInterests': 'View all interests →',
    'dashboard.openRecentlyViewed': 'View',
    'dashboard.sendInterest': 'Send Interest',
    'dashboard.noMessagesYet': 'No messages yet',
    'dashboard.chooseConversation': 'Choose a conversation from the list',
    'dashboard.selectChat': 'Select a chat to start messaging',
    'matches.title': 'Matches',
    'matches.find': 'Find Matches',
    'matches.subtitle': 'Browse compatible profiles, apply filters, and manage incoming interest requests.',
    'matches.filterProfiles': 'Filter Profiles',
    'matches.interestsReceived': 'Interests Received',
    'matches.interestsHelp': 'Accept to unlock chat, or reject to decline.',
    'matches.likedProfiles': 'Liked Profiles',
    'matches.likedHelp': 'People you liked will appear here.',
    'matches.reportedProfiles': 'Reported Profiles',
    'matches.reportedHelp': 'People you reported are listed here.',
    'matches.recommendedProfiles': 'Recommended Profiles',
    'matches.recommendedHelp': 'Based on your current filters and profile preferences.',
    'matches.noMatches': 'No matches found.',
    'matches.noLiked': 'No liked profiles yet.',
    'matches.noReported': 'No reported profiles.',
    'matches.noInterests': 'No interests received yet.',
    'matches.match': 'Match',
    'matches.like': '❤️ Like',
    'matches.unlike': '💔 Unlike',
    'matches.sendInterest': '💌 Send Interest',
    'matches.viewDetails': 'View details',
    'matches.skip': 'Skip',
    'matches.block': 'Block',
    'matches.unblock': 'Unblock',
    'matches.report': 'Report',
    'matches.accept': 'Accept',
    'matches.reject': 'Reject',
    'matches.sentYouInterest': 'Sent you an interest request',
    'matches.matchPercent': '{score}% Match',
    'matches.ageN/A': 'Age N/A',
    'matches.locationUnknown': 'Location unknown',
    'matches.professionUnknown': 'Profession not specified',
    'matches.noBio': 'No bio available.',
    'matches.unknownUser': 'Unknown User',
    'matches.userBlocked': 'User blocked.',
    'matches.reportedByTeam': 'Reported {name}. Our team will review.',
    'matches.liked': 'Liked {name}',
    'matches.matchWith': "It's a match with {name}!",
    'matches.interestSent': 'Interest sent to {name}!',
    'matches.interestAccepted': 'Interest accepted. Chat created.',
    'matches.interestRejected': 'Interest rejected.',
    'matches.failedInterest': 'Failed to send interest. Try again.',
    'matches.failedLike': 'Failed to like profile. Try again.',
    'matches.failedBlock': 'Failed to block user. Try again.',
    'matches.failedReport': 'Failed to report. Try again.',
    'matches.failedUpdateInterest': 'Could not update interest. Try again.',
    'matches.loadingError': 'Unable to load matches right now.',
    'matches.partialLoadError': 'Some matches data could not be loaded.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.login': 'Login',
    'auth.loggingIn': 'Logging in...',
    'auth.continueGoogle': 'Continue with Google',
    'auth.noAccount': 'No account?',
    'auth.signUp': 'Sign up',
    'auth.createAccount': 'Create account',
    'auth.creatingAccount': 'Creating your account...',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.startJourney': 'Start your journey to meaningful connections',
    'chat.pageTitle': 'Chat Page',
    'chat.messages': 'Messages',
    'chat.noChats': 'No chats yet. Accept interests to start chatting!',
    'chat.noMessagesYet': 'No messages yet',
    'chat.startConversation': 'Start the conversation!',
    'chat.selectChat': 'Select a chat to start messaging',
    'chat.noActiveChats': 'No active chats',
    'chat.chooseConversation': 'Choose a conversation from the list',
    'chat.chatWith': 'Chat with {name}',
    'chat.attachImage': 'Attach image',
    'chat.recordVoice': 'Record voice note',
    'chat.stopVoice': 'Stop recording and send voice note',
    'chat.focusMessageBox': 'Focus message box',
    'chat.writeMessage': 'Write a message...',
    'chat.send': 'Send',
    'chat.pressEnter': 'Press Enter to send • Shift+Enter for a new line',
    'chat.backToList': 'Back to chats list',
    'login.title': 'Login to MatchMitra',
    'signup.title': 'Create MatchMitra Account',
  },
  hi: {
    'language.label': 'भाषा',
    'language.english': 'अंग्रेज़ी',
    'language.hindi': 'हिंदी',
    'language.marathi': 'मराठी',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.matches': 'मैचेस',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.chat': 'चैट',
    'nav.testimonials': 'प्रशंसापत्र',
    'nav.logout': 'लॉगआउट',
    'footer.rights': '© {year} सभी अधिकार MatchMitra के पास सुरक्षित हैं।',
    'profile.rating': 'प्रोफ़ाइल रेटिंग',
    'profile.profileScoreHelp': 'यह रेटिंग बताती है कि प्रोफ़ाइल कितनी पूरी और भरोसेमंद दिखती है।',
    'profile.basicInfo': 'बुनियादी जानकारी',
    'profile.professional': 'पेशेवर जानकारी',
    'profile.aboutMe': 'मेरे बारे में',
    'profile.interests': 'रुचियाँ',
    'profile.family': 'परिवार',
    'profile.partnerPreferences': 'जीवनसाथी प्राथमिकताएँ',
    'profile.willingToRelocate': 'स्थान बदलने को तैयार',
    'profile.noValue': 'उपलब्ध नहीं',
    'profile.age': 'आयु',
    'profile.gender': 'लिंग',
    'profile.location': 'स्थान',
    'profile.height': 'ऊँचाई',
    'profile.maritalStatus': 'वैवाहिक स्थिति',
    'profile.profession': 'पेशा',
    'profile.education': 'शिक्षा',
    'profile.language': 'भाषा',
    'profile.religion': 'धर्म',
    'profile.caste': 'जाति',
    'profile.minAge': 'न्यूनतम आयु',
    'profile.maxAge': 'अधिकतम आयु',
    'profile.partnerLocation': 'स्थान',
    'profile.photo': 'प्रोफ़ाइल फ़ोटो',
    'profile.name': 'नाम',
    'profile.createProfile': 'अपनी प्रोफ़ाइल बनाएँ',
    'profile.editProfile': 'अपनी प्रोफ़ाइल संपादित करें',
    'profile.updateDetails': 'अपना विवरण कभी भी अपडेट करें।',
    'profile.completeDetails': 'बेहतर मैच पाने के लिए अपना विवरण पूरा करें।',
    'profile.completion': 'पूर्णता',
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.subtitle': 'एक साफ़ ओवरव्यू से अपने मैचिंग सफ़र को ट्रैक करें।',
    'dashboard.yourProfile': 'आपकी प्रोफ़ाइल',
    'dashboard.trustScore': 'विश्वास स्कोर',
    'dashboard.profileViews': 'प्रोफ़ाइल व्यू',
    'dashboard.pendingInterests': 'लंबित रुचियाँ',
    'dashboard.acceptedMatches': 'स्वीकृत मैच',
    'dashboard.activeChats': 'सक्रिय चैट',
    'dashboard.interestsReceived': 'मिली हुई रुचियाँ',
    'dashboard.interestsSubtitle': 'अनुरोध देखें और तैयार होने पर जवाब दें।',
    'dashboard.recentlyViewed': 'हाल ही में देखी गई',
    'dashboard.recentlyViewedSubtitle': 'वे प्रोफ़ाइल जिन्हें आपने हाल ही में खोला।',
    'dashboard.noRecentlyViewed': 'अभी कोई हाल ही में देखी गई प्रोफ़ाइल नहीं।',
    'dashboard.suggestedMatches': 'सुझाए गए मैच',
    'dashboard.suggestedSubtitle': 'आपकी प्राथमिकताओं से मेल खाते नए लोग।',
    'dashboard.openMatches': 'मैचेस पेज खोलें →',
    'dashboard.viewAllMatches': 'सभी मैच देखें →',
    'dashboard.recentMessages': 'हाल के संदेश',
    'dashboard.recentMessagesSubtitle': 'अपनी नई बातचीत पर एक त्वरित नज़र।',
    'dashboard.viewAllChats': 'सभी चैट देखें →',
    'dashboard.noActiveChats': 'अभी कोई सक्रिय चैट नहीं।',
    'dashboard.noMatches': 'कोई मैच उपलब्ध नहीं।',
    'dashboard.noInterests': 'अभी कोई रुचि प्राप्त नहीं हुई।',
    'dashboard.viewAllInterests': 'सभी रुचियाँ देखें →',
    'dashboard.openRecentlyViewed': 'देखें',
    'dashboard.sendInterest': 'रुचि भेजें',
    'dashboard.noMessagesYet': 'अभी कोई संदेश नहीं',
    'dashboard.chooseConversation': 'सूची से कोई बातचीत चुनें',
    'dashboard.selectChat': 'मैसेज शुरू करने के लिए चैट चुनें',
    'matches.title': 'मैचेस',
    'matches.find': 'मैच खोजें',
    'matches.subtitle': 'अनुकूल प्रोफ़ाइल ब्राउज़ करें, फ़िल्टर लगाएँ और आने वाले अनुरोधों को प्रबंधित करें।',
    'matches.filterProfiles': 'प्रोफ़ाइल फ़िल्टर',
    'matches.interestsReceived': 'प्राप्त रुचियाँ',
    'matches.interestsHelp': 'चैट खोलने के लिए स्वीकार करें, या अस्वीकार करें।',
    'matches.likedProfiles': 'पसंद की गई प्रोफ़ाइल',
    'matches.likedHelp': 'आपकी पसंद की गई प्रोफ़ाइल यहाँ दिखेंगी।',
    'matches.reportedProfiles': 'रिपोर्ट की गई प्रोफ़ाइल',
    'matches.reportedHelp': 'आपके द्वारा रिपोर्ट की गई प्रोफ़ाइल यहाँ हैं।',
    'matches.recommendedProfiles': 'सुझाई गई प्रोफ़ाइल',
    'matches.recommendedHelp': 'आपके फ़िल्टर और प्राथमिकताओं के आधार पर।',
    'matches.noMatches': 'कोई मैच नहीं मिला।',
    'matches.noLiked': 'अभी कोई पसंद की गई प्रोफ़ाइल नहीं।',
    'matches.noReported': 'अभी कोई रिपोर्ट की गई प्रोफ़ाइल नहीं।',
    'matches.noInterests': 'अभी कोई रुचि प्राप्त नहीं हुई।',
    'matches.match': 'मैच',
    'matches.like': '❤️ पसंद',
    'matches.unlike': '💔 अनलाइक',
    'matches.sendInterest': '💌 रुचि भेजें',
    'matches.viewDetails': 'विवरण देखें',
    'matches.skip': 'स्किप',
    'matches.block': 'ब्लॉक',
    'matches.unblock': 'अनब्लॉक',
    'matches.report': 'रिपोर्ट',
    'matches.accept': 'स्वीकार करें',
    'matches.reject': 'अस्वीकार करें',
    'matches.sentYouInterest': 'आपको रुचि भेजी है',
    'matches.matchPercent': '{score}% मैच',
    'matches.ageN/A': 'आयु उपलब्ध नहीं',
    'matches.locationUnknown': 'स्थान उपलब्ध नहीं',
    'matches.professionUnknown': 'पेशा उपलब्ध नहीं',
    'matches.noBio': 'बायो उपलब्ध नहीं।',
    'matches.unknownUser': 'अज्ञात उपयोगकर्ता',
    'matches.userBlocked': 'उपयोगकर्ता ब्लॉक किया गया।',
    'matches.reportedByTeam': '{name} को रिपोर्ट किया गया। हमारी टीम समीक्षा करेगी।',
    'matches.liked': '{name} को पसंद किया गया',
    'matches.matchWith': 'यह {name} के साथ मैच है!',
    'matches.interestSent': '{name} को रुचि भेजी गई!',
    'matches.interestAccepted': 'रुचि स्वीकार की गई। चैट बनाई गई।',
    'matches.interestRejected': 'रुचि अस्वीकार की गई।',
    'matches.failedInterest': 'रुचि भेजने में असफल। कृपया पुनः प्रयास करें।',
    'matches.failedLike': 'प्रोफ़ाइल पसंद करने में असफल। कृपया पुनः प्रयास करें।',
    'matches.failedBlock': 'उपयोगकर्ता को ब्लॉक करने में असफल। कृपया पुनः प्रयास करें।',
    'matches.failedReport': 'रिपोर्ट करने में असफल। कृपया पुनः प्रयास करें।',
    'matches.failedUpdateInterest': 'रुचि अपडेट नहीं हो सकी। कृपया पुनः प्रयास करें।',
    'matches.loadingError': 'अभी मैचेस लोड नहीं हो सके।',
    'matches.partialLoadError': 'कुछ मैच डेटा लोड नहीं हो सके।',
    'chat.pageTitle': 'चैट पेज',
    'chat.messages': 'संदेश',
    'chat.noChats': 'अभी कोई चैट नहीं। चैट शुरू करने के लिए रुचि स्वीकार करें!',
    'chat.noMessagesYet': 'अभी कोई संदेश नहीं',
    'chat.startConversation': 'बातचीत शुरू करें!',
    'chat.selectChat': 'मैसेज शुरू करने के लिए चैट चुनें',
    'chat.noActiveChats': 'कोई सक्रिय चैट नहीं',
    'chat.chooseConversation': 'सूची से कोई बातचीत चुनें',
    'chat.chatWith': '{name} के साथ चैट',
    'chat.attachImage': 'छवि जोड़ें',
    'chat.recordVoice': 'वॉइस नोट रिकॉर्ड करें',
    'chat.stopVoice': 'रिकॉर्डिंग रोकें और वॉइस नोट भेजें',
    'chat.focusMessageBox': 'मैसेज बॉक्स पर जाएँ',
    'chat.writeMessage': 'संदेश लिखें...',
    'chat.send': 'भेजें',
    'chat.pressEnter': 'भेजने के लिए Enter दबाएँ • नई लाइन के लिए Shift+Enter',
    'chat.backToList': 'चैट सूची पर वापस जाएँ',
    'login.title': 'MatchMitra में लॉगिन करें',
    'signup.title': 'MatchMitra खाता बनाएँ',
  },
  mr: {
    'language.label': 'भाषा',
    'language.english': 'इंग्रजी',
    'language.hindi': 'हिंदी',
    'language.marathi': 'मराठी',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.matches': 'मॅचेस',
    'nav.profile': 'प्रोफाइल',
    'nav.chat': 'चॅट',
    'nav.testimonials': 'प्रशंसापत्रे',
    'nav.logout': 'लॉगआउट',
    'footer.rights': '© {year} सर्व हक्क MatchMitra कडे राखीव आहेत.',
    'profile.rating': 'प्रोफाइल रेटिंग',
    'profile.profileScoreHelp': 'हे रेटिंग प्रोफाइल किती पूर्ण आणि विश्वासार्ह दिसते हे सूचित करते.',
    'profile.basicInfo': 'मूलभूत माहिती',
    'profile.professional': 'व्यावसायिक माहिती',
    'profile.aboutMe': 'माझ्याबद्दल',
    'profile.interests': 'स्वारस्ये',
    'profile.family': 'कुटुंब',
    'profile.partnerPreferences': 'जीवनसाथी प्राधान्ये',
    'profile.willingToRelocate': 'स्थलांतरासाठी तयार',
    'profile.noValue': 'उपलब्ध नाही',
    'profile.age': 'वय',
    'profile.gender': 'लिंग',
    'profile.location': 'स्थान',
    'profile.height': 'उंची',
    'profile.maritalStatus': 'वैवाहिक स्थिती',
    'profile.profession': 'व्यवसाय',
    'profile.education': 'शिक्षण',
    'profile.language': 'भाषा',
    'profile.religion': 'धर्म',
    'profile.caste': 'जात',
    'profile.minAge': 'किमान वय',
    'profile.maxAge': 'कमाल वय',
    'profile.partnerLocation': 'स्थान',
    'profile.photo': 'प्रोफाइल फोटो',
    'profile.name': 'नाव',
    'profile.createProfile': 'तुमची प्रोफाइल तयार करा',
    'profile.editProfile': 'तुमची प्रोफाइल संपादित करा',
    'profile.updateDetails': 'तुमचे तपशील कधीही अपडेट करा.',
    'profile.completeDetails': 'उत्तम मॅचेससाठी तुमचे तपशील पूर्ण करा.',
    'profile.completion': 'पूर्णता',
    'dashboard.title': 'डॅशबोर्ड',
    'dashboard.subtitle': 'एकाच सुंदर आढाव्यातून तुमचा मॅचिंग प्रवास ट्रॅक करा.',
    'dashboard.yourProfile': 'तुमची प्रोफाइल',
    'dashboard.trustScore': 'विश्वास गुण',
    'dashboard.profileViews': 'प्रोफाइल दृश्ये',
    'dashboard.pendingInterests': 'प्रलंबित स्वारस्ये',
    'dashboard.acceptedMatches': 'स्वीकृत मॅचेस',
    'dashboard.activeChats': 'सक्रिय चॅट्स',
    'dashboard.interestsReceived': 'मिळालेली स्वारस्ये',
    'dashboard.interestsSubtitle': 'विनंत्या तपासा आणि तयार झाल्यावर प्रतिसाद द्या.',
    'dashboard.recentlyViewed': 'अलीकडे पाहिलेले',
    'dashboard.recentlyViewedSubtitle': 'तुम्ही अलीकडे उघडलेल्या प्रोफाइल्स.',
    'dashboard.noRecentlyViewed': 'अजून अलीकडे पाहिलेले प्रोफाइल नाही.',
    'dashboard.suggestedMatches': 'सुचवलेले मॅचेस',
    'dashboard.suggestedSubtitle': 'तुमच्या प्राधान्यांशी जुळणारे नवीन लोक.',
    'dashboard.openMatches': 'मॅचेस पेज उघडा →',
    'dashboard.viewAllMatches': 'सर्व मॅचेस पहा →',
    'dashboard.recentMessages': 'अलीकडचे संदेश',
    'dashboard.recentMessagesSubtitle': 'तुमच्या नव्या संभाषणाचा झटपट आढावा.',
    'dashboard.viewAllChats': 'सर्व चॅट्स पहा →',
    'dashboard.noActiveChats': 'अजून सक्रिय चॅट नाही.',
    'dashboard.noMatches': 'मॅच उपलब्ध नाही.',
    'dashboard.noInterests': 'अजून स्वारस्य मिळालेले नाही.',
    'dashboard.viewAllInterests': 'सर्व स्वारस्ये पहा →',
    'dashboard.openRecentlyViewed': 'पहा',
    'dashboard.sendInterest': 'स्वारस्य पाठवा',
    'dashboard.noMessagesYet': 'अजून संदेश नाहीत',
    'dashboard.chooseConversation': 'सूचीतून संभाषण निवडा',
    'dashboard.selectChat': 'मेसेजिंग सुरू करण्यासाठी चॅट निवडा',
    'matches.title': 'मॅचेस',
    'matches.find': 'मॅच शोधा',
    'matches.subtitle': 'योग्य प्रोफाइल्स पहा, फिल्टर लावा आणि येणाऱ्या स्वारस्य विनंत्या सांभाळा.',
    'matches.filterProfiles': 'प्रोफाइल फिल्टर',
    'matches.interestsReceived': 'मिळालेली स्वारस्ये',
    'matches.interestsHelp': 'चॅट उघडण्यासाठी स्वीकारा, किंवा नाकार करा.',
    'matches.likedProfiles': 'आवडलेल्या प्रोफाइल्स',
    'matches.likedHelp': 'तुम्ही आवडलेल्या लोकांचे नाव येथे दिसेल.',
    'matches.reportedProfiles': 'रिपोर्ट केलेले प्रोफाइल्स',
    'matches.reportedHelp': 'तुम्ही रिपोर्ट केलेले लोक येथे दिसतील.',
    'matches.recommendedProfiles': 'शिफारस केलेले प्रोफाइल्स',
    'matches.recommendedHelp': 'तुमच्या फिल्टर्स आणि प्राधान्यांवर आधारित.',
    'matches.noMatches': 'कोणतेही मॅच सापडले नाहीत.',
    'matches.noLiked': 'अजून आवडलेले प्रोफाइल नाही.',
    'matches.noReported': 'अजून रिपोर्ट केलेले प्रोफाइल नाही.',
    'matches.noInterests': 'अजून स्वारस्य मिळालेले नाही.',
    'matches.match': 'मॅच',
    'matches.like': '❤️ लाईक',
    'matches.unlike': '💔 अनलाईक',
    'matches.sendInterest': '💌 स्वारस्य पाठवा',
    'matches.viewDetails': 'तपशील पहा',
    'matches.skip': 'स्किप',
    'matches.block': 'ब्लॉक',
    'matches.unblock': 'अनब्लॉक',
    'matches.report': 'रिपोर्ट',
    'matches.accept': 'स्वीकारा',
    'matches.reject': 'नाकारा',
    'matches.sentYouInterest': 'तुम्हाला स्वारस्य पाठवले आहे',
    'matches.matchPercent': '{score}% मॅच',
    'matches.ageN/A': 'वय उपलब्ध नाही',
    'matches.locationUnknown': 'स्थान उपलब्ध नाही',
    'matches.professionUnknown': 'व्यवसाय उपलब्ध नाही',
    'matches.noBio': 'बायो उपलब्ध नाही.',
    'matches.unknownUser': 'अज्ञात वापरकर्ता',
    'matches.userBlocked': 'वापरकर्ता ब्लॉक केला.',
    'matches.reportedByTeam': '{name} ला रिपोर्ट केले. आमची टीम तपासेल.',
    'matches.liked': '{name} ला लाईक केले',
    'matches.matchWith': '{name} सोबत मॅच झाले!',
    'matches.interestSent': '{name} ला स्वारस्य पाठवले!',
    'matches.interestAccepted': 'स्वारस्य स्वीकारले. चॅट तयार केले.',
    'matches.interestRejected': 'स्वारस्य नाकारले.',
    'matches.failedInterest': 'स्वारस्य पाठवता आले नाही. कृपया पुन्हा प्रयत्न करा.',
    'matches.failedLike': 'प्रोफाइल लाईक करता आले नाही. कृपया पुन्हा प्रयत्न करा.',
    'matches.failedBlock': 'वापरकर्त्याला ब्लॉक करता आले नाही. कृपया पुन्हा प्रयत्न करा.',
    'matches.failedReport': 'रिपोर्ट करता आला नाही. कृपया पुन्हा प्रयत्न करा.',
    'matches.failedUpdateInterest': 'स्वारस्य अपडेट करता आले नाही. कृपया पुन्हा प्रयत्न करा.',
    'matches.loadingError': 'आत्ता मॅचेस लोड करता आले नाहीत.',
    'matches.partialLoadError': 'काही मॅच डेटा लोड होऊ शकला नाही.',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.login': 'लॉगिन',
    'auth.loggingIn': 'लॉगिन होत आहे...',
    'auth.continueGoogle': 'गुगलसह सुरू ठेवा',
    'auth.noAccount': 'खाते नाही?',
    'auth.signUp': 'साइन अप',
    'auth.createAccount': 'खाते तयार करा',
    'auth.creatingAccount': 'तुमचे खाते तयार केले जात आहे...',
    'auth.alreadyHaveAccount': 'आधीच खाते आहे?',
    'auth.startJourney': 'अर्थपूर्ण जोडण्यांचा तुमचा प्रवास सुरू करा',
    'chat.pageTitle': 'चॅट पेज',
    'chat.messages': 'संदेश',
    'chat.noChats': 'अजून चॅट नाहीत. चॅट सुरू करण्यासाठी स्वारस्य स्वीकारा!',
    'chat.noMessagesYet': 'अजून संदेश नाहीत',
    'chat.startConversation': 'संभाषण सुरू करा!',
    'chat.selectChat': 'मेसेजिंग सुरू करण्यासाठी चॅट निवडा',
    'chat.noActiveChats': 'सक्रिय चॅट नाहीत',
    'chat.chooseConversation': 'सूचीतून संभाषण निवडा',
    'chat.chatWith': '{name} सोबत चॅट',
    'chat.attachImage': 'प्रतिमा जोडा',
    'chat.recordVoice': 'व्हॉइस नोट रेकॉर्ड करा',
    'chat.stopVoice': 'रेकॉर्डिंग थांबवा आणि व्हॉइस नोट पाठवा',
    'chat.focusMessageBox': 'मेसेज बॉक्सवर जा',
    'chat.writeMessage': 'संदेश लिहा...',
    'chat.send': 'पाठवा',
    'chat.pressEnter': 'पाठवण्यासाठी Enter दाबा • नवीन ओळीसाठी Shift+Enter',
    'chat.backToList': 'चॅट यादीवर परत जा',
    'login.title': 'MatchMitra मध्ये लॉगिन करा',
    'signup.title': 'MatchMitra खाते तयार करा',
  },
};

const LanguageContext = createContext(null);

const applyParams = (template, params = {}) =>
  Object.entries(params).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    template,
  );

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    if (typeof window === 'undefined') return 'en';
    return localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'en';
  });

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language === 'mr' ? 'mr' : language === 'hi' ? 'hi' : 'en';
  }, [language]);

  const t = useMemo(() => {
    return (key, params) => {
      const base = translations[language]?.[key] ?? translations.en[key] ?? key;
      return applyParams(base, params);
    };
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t,
      supportedLanguages,
    }),
    [language, t],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
};
